language: php

env:
  nette-2.1:
    - "NETTE=default"
  nette-2.2:
    - "NETTE=nette-2.2"
  nette-dev:
    - "NETTE=nette-dev"

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
#  - hhvm

matrix:
  allow_failures:
    - env: nette-dev

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script: php tests/lint.php src/Kdyby/ tests/KdybyTests/ && VERBOSE=true ./tests/run-tests.sh -s tests/KdybyTests/
